/**
 * Score Manager
 * Score Manager
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Instrument } from './instrument';


export interface Instruments { 
    content?: Array<Instrument>;
    number?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
}

