/**
 * Score Manager
 * Score Manager
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Score { 
    id?: number;
    title: string;
    composer?: string;
    duration?: number;
    year?: number;
}

