openapi: 3.0.3
info:
  title: Score Manager
  description: Score Manager
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /scores:
    get:
      tags:
        - scores
      summary: Get all scores
      operationId: getAllScores
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scores'
    post:
      tags:
        - scores
      summary: Add a new score
      operationId: addScore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Score'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Score'
  /instruments:
    get:
      tags:
        - instruments
      summary: Get all instruments
      operationId: getAllInstruments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instruments'
    post:
      tags:
        - instruments
      summary: Add a new instrument
      operationId: addInstrument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Instrument'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instrument'
components:
  schemas:
    Page:
      type: object
      properties:
        number:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer
    Score:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
      required:
        - title
    Scores:
      allOf:
        - $ref: '#/components/schemas/Page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Score'
    Instrument:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name
    Instruments:
      allOf:
        - $ref: '#/components/schemas/Page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Instrument'
